import { useQuery } from "@tanstack/react-query";
import { ArrowRight, CheckCircle2, CircleAlert, Clock3, ShieldCheck, Sparkles } from "lucide-react";

import { apiGet } from "@/lib/api";
import type { CfoResponse, Insight } from "@/lib/types";

export default function Cfo() {
  const query = useQuery({ queryKey: ["cfo"], queryFn: () => apiGet<CfoResponse>("/dashboard/cfo"), retry: false });
  const data = query.data;
  return <div className="space-y-7" data-testid="cfo-page">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-rose-600" data-testid="cfo-eyebrow">Decide</p><h1 className="font-heading text-3xl font-bold tracking-[-0.04em] text-slate-950" data-testid="cfo-title">AI CFO</h1><p className="mt-2 max-w-2xl text-sm text-slate-500" data-testid="cfo-description">Clear, explainable next steps built from the financial signals already in your ledger.</p></div><div className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700" data-testid="cfo-engine-status"><ShieldCheck size={15} />Rules engine active</div></section>
    {query.isError ? <div className="rounded-lg border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800" data-testid="cfo-data-error">The CFO brief is unavailable. Refresh to reconnect to the deterministic insight engine.</div> : data ? <>
      <section className="rounded-lg border border-slate-200 bg-white p-5 sm:p-6" data-testid="cfo-brief-banner"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-rose-50 text-rose-600"><Sparkles size={19} /></div><div><p className="font-heading text-sm font-bold text-slate-900" data-testid="cfo-brief-title">The brief, without the black box</p><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500" data-testid="cfo-disclaimer">{data.disclaimer}</p></div></div></section>
      <section className="grid gap-4 lg:grid-cols-3" data-testid="cfo-insights-grid">{data.insights.map((insight) => <InsightCard key={insight.id} insight={insight} />)}</section>
      <section className="rounded-lg border border-dashed border-slate-300 bg-slate-50 p-5 sm:p-6" data-testid="ollama-ready-card"><div className="flex items-start gap-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-white text-slate-500"><ShieldCheck size={17} /></div><div><p className="font-heading text-sm font-bold text-slate-800" data-testid="ollama-ready-title">Ready for local Ollama later</p><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500" data-testid="ollama-ready-copy">The insight provider is isolated behind a backend interface. A local model can explain the same validated facts later; it will not own reconciliation or forecasting math.</p></div></div></section>
    </> : <div className="rounded-lg border border-slate-200 bg-white p-8 text-sm text-slate-500" data-testid="cfo-loading">Preparing your CFO brief…</div>}
  </div>;
}

function InsightCard({ insight }: { insight: Insight }) { const meta = { high: { label: "Priority · high", className: "bg-rose-50 text-rose-700", icon: <CircleAlert size={14} /> }, medium: { label: "Priority · medium", className: "bg-amber-50 text-amber-700", icon: <Clock3 size={14} /> }, low: { label: "Priority · low", className: "bg-emerald-50 text-emerald-700", icon: <CheckCircle2 size={14} /> } }[insight.priority]; return <article className="flex flex-col rounded-lg border border-slate-200 bg-white p-5 transition-transform hover:-translate-y-0.5 hover:shadow-md" data-testid={`insight-card-${insight.id}`}><div className="flex items-center justify-between"><span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[10px] font-bold ${meta.className}`} data-testid={`insight-priority-${insight.id}`}>{meta.icon}{meta.label}</span><span className="font-mono text-[10px] text-slate-400" data-testid={`insight-source-${insight.id}`}>{insight.source}</span></div><h2 className="mt-5 font-heading text-lg font-bold leading-6 text-slate-900" data-testid={`insight-title-${insight.id}`}>{insight.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-500" data-testid={`insight-body-${insight.id}`}>{insight.body}</p><div className="mt-6 border-t border-slate-100 pt-4"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400" data-testid={`insight-metric-label-${insight.id}`}>{insight.metric_label}</p><p className="mt-1 font-mono text-lg font-medium text-slate-900" data-testid={`insight-metric-value-${insight.id}`}>{insight.metric_value}</p><button type="button" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-rose-700 transition-transform hover:translate-x-0.5" data-testid={`insight-action-${insight.id}`}>{insight.action}<ArrowRight size={14} /></button></div></article>; }