import type { ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, Info, TrendingUp } from "lucide-react";

import { apiGet } from "@/lib/api";
import { formatINR } from "@/lib/format";
import type { ForecastResponse } from "@/lib/types";

export default function Forecast() {
  const query = useQuery({ queryKey: ["forecast"], queryFn: () => apiGet<ForecastResponse>("/dashboard/forecast"), retry: false });
  const data = query.data;
  return <div className="space-y-7" data-testid="forecast-page">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-rose-600" data-testid="forecast-eyebrow">Predict</p><h1 className="font-heading text-3xl font-bold tracking-[-0.04em] text-slate-950" data-testid="forecast-title">Cash-flow forecast</h1><p className="mt-2 max-w-2xl text-sm text-slate-500" data-testid="forecast-description">A directional view of your cash position, grounded in observed ledger movement.</p></div><span className="inline-flex items-center gap-2 self-start rounded-md bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600 sm:self-auto" data-testid="forecast-confidence"><Info size={14} />{data?.confidence_label ?? "Calculating range"}</span></section>
    {query.isError ? <div className="rounded-lg border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800" data-testid="forecast-data-error">The forecast model is unavailable. Try refreshing the workspace.</div> : data ? <>
      <section className="grid gap-3 md:grid-cols-3" data-testid="forecast-summary-cards"><ForecastMetric label="Today" value={formatINR(data.current_cash)} detail="Current modeled cash" icon={<TrendingUp size={16} />} testId="forecast-current-card" /><ForecastMetric label="Six-week outlook" value={formatINR(data.ending_cash)} detail={`${data.change_percent >= 0 ? "+" : ""}${data.change_percent}% expected change`} icon={data.change_percent >= 0 ? <ArrowUpRight size={16} /> : <ArrowDownRight size={16} />} testId="forecast-ending-card" /><ForecastMetric label="Horizon" value={`${data.horizon_weeks} weeks`} detail="Holt trend model" icon={<Info size={16} />} testId="forecast-horizon-card" /></section>
      <section className="rounded-lg border border-slate-200 bg-white" data-testid="forecast-chart-card"><div className="flex flex-col justify-between gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:p-6"><div><h2 className="font-heading text-lg font-bold text-slate-900" data-testid="forecast-chart-title">Projected cash position</h2><p className="mt-1 text-xs text-slate-500" data-testid="forecast-chart-subtitle">Historical actuals with a six-week modeled outlook</p></div><div className="flex items-center gap-4 text-[11px] text-slate-500"><span className="flex items-center gap-1.5" data-testid="forecast-legend-actual"><span className="h-2 w-2 rounded-full bg-slate-400" />Actual</span><span className="flex items-center gap-1.5" data-testid="forecast-legend-forecast"><span className="h-2 w-2 rounded-full bg-rose-600" />Forecast</span></div></div><div className="h-[340px] w-full p-3 sm:p-6" data-testid="forecast-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.points} margin={{ top: 12, right: 8, left: 8, bottom: 0 }}><defs><linearGradient id="forecastFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e11d48" stopOpacity={0.18} /><stop offset="100%" stopColor="#e11d48" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#eef2f6" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} /><YAxis tickFormatter={(value: number) => `₹${Math.round(value / 1000)}k`} tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} width={42} /><Tooltip content={<ForecastTooltip />} /><Area type="monotone" dataKey="actual" stroke="#94a3b8" fill="transparent" strokeWidth={2} connectNulls={false} /><Area type="monotone" dataKey="forecast" stroke="#e11d48" fill="url(#forecastFill)" strokeWidth={2.5} connectNulls={false} /></AreaChart></ResponsiveContainer></div><div className="flex items-start gap-2 border-t border-slate-100 px-5 py-4 text-[11px] leading-5 text-slate-500 sm:px-6" data-testid="forecast-method-note"><Info size={14} className="mt-0.5 shrink-0 text-slate-400" />Model uses a Holt trend on weekly net cash movement. The range is directional, not a guarantee.</div></section>
    </> : <div className="rounded-lg border border-slate-200 bg-white p-8 text-sm text-slate-500" data-testid="forecast-loading">Calculating cash outlook…</div>}
  </div>;
}

function ForecastMetric({ label, value, detail, icon, testId }: { label: string; value: string; detail: string; icon: ReactNode; testId: string }) { return <div className="rounded-lg border border-slate-200 bg-white p-4" data-testid={testId}><div className="flex items-center justify-between"><p className="text-xs text-slate-400" data-testid={`${testId}-label`}>{label}</p><span className="text-rose-600">{icon}</span></div><p className="mt-4 font-mono text-xl font-medium text-slate-900" data-testid={`${testId}-value`}>{value}</p><p className="mt-1 text-[11px] text-slate-500" data-testid={`${testId}-detail`}>{detail}</p></div>; }
function ForecastTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value?: number; dataKey?: string }>; label?: string }) { if (!active || !payload?.length) return null; return <div className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs shadow-lg" data-testid="forecast-tooltip"><p className="mb-1 text-slate-400">{label}</p>{payload.map((entry) => <p key={entry.dataKey} className="font-mono font-medium text-slate-800">{entry.dataKey === "forecast" ? "Forecast" : "Actual"}: {formatINR(entry.value ?? 0)}</p>)}</div>; }